### ISSUE TITLE
Can we avoid such classes like `TEBaseStore` in favor of Protocols? It will allow to use composition over inheritance

### ISSUE THREAD

**Issue by goncharik** [techery/FLUX#1]

**Comment by fuzza** [comment]
We need base store class to be sure that default state is set when store is initialized. 
As for actions and states, we are going to use machine-generated immutable models, so I've already deleted that classes in current dev version.

**Comment by sergeyzenchenko** [comment]
Also sometimes it's better to force user to use inheritance. I can't imagine the case when we need compose store logic with something else.
